apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - rbac.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml
  - namespace.yaml
  - sealed-basic-auth.yaml
